sudo: false
language: python
notifications:
  email:
    recipients:
      - chenjiandongx@qq.com
    on_success: always # default: change
    on_failure: always # default: always
python:
  - 3.6
  - 3.5
  - 3.4
before_install:
  - pip install -r requirements.txt
script:
  - make tests
